services:
  backend:
    build: .
    env_file: [.env]
    ports: ["8000:8000"]
    depends_on: [db]
    volumes: [".:/app"]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:




